# generated by datamodel-codegen:
#   filename:  group_msg.json
#   timestamp: 2023-04-07T14:05:16+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field


class FromType(Enum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class GroupInfo(BaseModel):
    GroupCard: str
    GroupCode: int
    GroupInfoSeq: int
    GroupLevel: int
    GroupRank: int
    GroupType: int
    GroupName: str


class MsgHead(BaseModel):
    FromUin: int
    ToUin: int
    FromType: FromType = Field(..., description="消息来源类型 3私聊 2群组 1好友")
    SenderUin: int
    SenderNick: str
    MsgType: int
    C2cCmd: int
    MsgSeq: int
    MsgTime: int
    MsgRandom: int
    MsgUid: int
    GroupInfo: Optional[GroupInfo] = None
    C2CTempMessageHead: Optional[Any] = None


class AtUinList(BaseModel):
    QQNick: str
    QQUid: int


class Image(BaseModel):
    FileId: int
    FileMd5: str
    FileSize: int
    Url: str


class Video(BaseModel):
    FileMd5: str
    FileSize: int
    Url: str


class Voice(BaseModel):
    FileMd5: str
    FileSize: int
    Url: str


class MsgBody(BaseModel):
    SubMsgType: int = Field(
        ..., description="0为单一或复合类型消息(文字 At 图片 自由组合), 12 Xml消息 19 Video消息 51 JSON卡片消息"
    )
    Content: str
    AtUinLists: Optional[List[AtUinList]] = None
    Images: Optional[List[Image]] = None
    Video: Optional[Video] = None
    Voice: Optional[Voice] = None


class EventData(BaseModel):
    MsgHead: MsgHead
    MsgBody: MsgBody


class EventName(Enum):
    ON_EVENT_QQNT_NEW_MSG = "ON_EVENT_QQNT_NEW_MSG"
    ON_EVENT_GROUP_NEW_MSG = "ON_EVENT_GROUP_NEW_MSG"
    ON_EVENT_GROUP_JOIN = "ON_EVENT_GROUP_JOIN"
    ON_EVENT_GROUP_EXIT = "ON_EVENT_GROUP_EXIT"


class CurrentPacket(BaseModel):
    EventData: EventData
    EventName: EventName


class GroupMsg(BaseModel):
    CurrentPacket: CurrentPacket
    CurrentQQ: int = Field(..., description="Bot QQ号")
